import type { Timestamp } from 'firebase/firestore';

export interface Service {
  id: string;
  name: string;
  description: string;
  price: number;
}

export interface Booking {
  id?: string; // Optional because it's generated by Firestore
  name: string;
  email: string;
  phone: string;
  address: string;
  serviceId: string;
  serviceName: string; // Denormalized for easier display
  servicePrice: number; // Denormalized for easier display
  date: Date; // Use JS Date for form, convert to Timestamp for Firestore
  time: string;
  comments: string;
  status: 'pending' | 'confirmed' | 'paid' | 'completed' | 'cancelled';
  createdAt: Timestamp;
  paymentIntentId?: string; // Optional for Stripe integration
}
